In [2]:
import pandas as pd

In [3]:
# train_raw_18 = pd.read_csv("train_pre_18_fix_index.csv")
# X_test_18 = pd.read_csv("test_pre_18_fix_index.csv")

# train_raw_13 = pd.read_csv("train_pre_13.csv")
# X_test_13 = pd.read_csv("test_pre_13.csv")

train_raw_13 = pd.read_csv("train_pre_13_add_more_ftrs.csv")
X_test_13 = pd.read_csv("test_pre_13_add_more_ftrs.csv")

In [3]:
other_all_feature = pd.read_csv("all_features_18_other_features_2.csv", index_col=None)
print(other_all_feature.shape)
del other_all_feature['Unnamed: 0']
print(other_all_feature.shape)

(1938653, 7)
(1938653, 6)

In [5]:
# all_features_18 = pd.concat([train_raw_18.drop("fraud_ind", axis=1), X_test_18], axis=0)
all_features_13 = pd.concat([train_raw_13.drop("fraud_ind", axis=1), X_test_13], axis=0)

In [6]:
# print(train_raw_18.shape)
print(train_raw_13.shape)
# print(all_features_18.shape)
print(all_features_13.shape)

(1516988, 103)
(1938653, 102)

In [6]:
# train_raw_18.head()

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_7,latent_9,latent_10,latent_11,latent_12,latent_13,latent_14,latent_15,latent_16,fraud_ind
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.0,0.000,0.000,0
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.236,0.218,0.493,0.282,0.355,0.678,0.0,0.093,0.000,0
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.0,0.000,0.000,0
3,6716,157159,29967,1016.11,62,172946,247,50436,3281,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.0,0.000,0.030,0
4,5975,105985,81305,713.66,62,182129,263,93775,5817,102,...,0.219,0.262,0.000,0.839,0.000,0.000,0.0,0.000,0.083,0

In [4]:
train_raw_13.head()

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,bacno_cano_conam_rolling_14_window_mean,bacno_cano_conam_rolling_7_window_mean,bacno_cano_conam_rolling_3_window_mean,bacno_cano_7_times_conam_max_by_no,bacno_cano_conam_rolling_14_window_max,bacno_cano_14_times_conam_max_by_no,bacno_cano_conam_cumsum_mean.1,bacno_cano_recent_no_5_loctm_acc_min_diff,bacno_cano_no_mean_loctm_acc_min_diff,fraud_ind
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,601.579,524.787,575.297,2385.75,1458.33,2385.75,561.301096,189.563333,1620.892616,0
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,383.249,354.677,234.660,1881.93,812.26,1881.93,355.962083,967.920000,5288.661364,0
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,568.570,556.070,550.040,776.57,683.25,1304.96,552.063333,1939.836667,6931.104902,0
3,6716,157159,29967,1016.11,62,172946,247,50436,3281,102,...,0.000,0.000,0.000,1310.49,0.00,1830.62,0.000000,0.000000,2263.099107,0
4,5975,105985,81305,713.66,62,182129,263,93775,5817,102,...,814.140,814.140,814.140,1159.29,814.14,1159.29,814.140000,0.000000,2009.279301,0

In [8]:
other_all_feature.head()

,bacno_cano_7_times_conam_max_by_no,bacno_cano_conam_rolling_14_window_max,bacno_cano_14_times_conam_max_by_no,bacno_cano_conam_cumsum_mean,bacno_cano_recent_no_5_loctm_acc_min_diff,bacno_cano_no_mean_loctm_acc_min_diff
0,2385.75,1458.33,2385.75,561.301096,189.563333,1620.892616
1,1881.93,812.26,1881.93,355.962083,967.920000,5288.661364
2,776.57,683.25,1304.96,552.063333,1939.836667,6931.104902
3,1310.49,0.00,1830.62,0.000000,0.000000,2263.099107
4,1159.29,814.14,1159.29,814.140000,0.000000,2009.279301

### 將特徵合併至pre13

In [8]:
pd.read_csv("importance_model_pre_18_fix_index.csv").sort_values("importance", ascending=False)

                                     feature_name  importance
1                                           bacno       73901
2                                            cano       34634
7                                           mchno       17649
0                                           acqic       17589
6                                             mcc       14249
8                                           scity        9059
3                                           conam        7905
23                              cano_value_counts        6826
22                             bacno_value_counts        5019
72                  bacno_cnt_by_locdt_loctm_hour        4683
40                            conam_mean_by_bacno        3706
51                            conam_mean_by_locdt        3384
52                        loctm_cnt_mean_by_bacno        3007
53                         loctm_cnt_mean_by_cano        2774
41                             conam_mean_by_cano        2505
24                             mchno_value_counts        1722
9                                           stocn        1667
73                        conam_is_0_cnt_by_bacno        1646
74                                       latent_0        1644
5                                           loctm        1504
18                        loctm_hour_value_counts        1423
4                                           csmcu        1420
11                                      loctm_min        1403
60                                 bacon_cano_cnt        1365
68   bacno_cano_7_sleep_time_conam_lower_3000_cnt        1329
82                                      latent_10        1323
70         bacno_cano_no_recent_7_conam_pos_trend        1320
12                                      loctm_sec        1292
17                             loctm_value_counts        1271
31                             stscd_value_counts        1237
..                                            ...         ...
43                            conam_mean_by_acqic         405
80                                       latent_7         396
75                                       latent_1         387
49                            conam_mean_by_scity         387
81                                       latent_9         368
34                             csmcu_value_counts         355
56                          loctm_cnt_mean_by_mcc         354
19                             csmcu_cnt_by_stocn         349
37                               prime_time_fraud         347
15                           bacno_u_cnt_by_acqic         346
25                             acqic_value_counts         340
13                                     conam_is_0         331
67             bacno_cano_14_times_sleep_time_cnt         310
26                               mcc_value_counts         300
44                              conam_mean_by_mcc         292
20                             csmcu_cnt_by_scity         291
10                                     loctm_hour         252
48                            conam_mean_by_stocn         190
58                        loctm_cnt_mean_by_csmcu         188
69  bacno_cano_14_sleep_time_conam_lower_3000_cnt         162
16                                    conam_level         162
50                            conam_mean_by_csmcu         101
86                                      latent_14          93
35                         flg_3dsmk_value_counts          73
27                             contp_value_counts          44
28                             etymd_value_counts          31
33                             hcefg_value_counts          15
36                              prime_time_normal           3
39                    sleep_time_conam_lower_3000           2
38                                     sleep_time           0

[89 rows x 2 columns]

#### 1. bacno_cano_recent_no_5_loctm_acc_min_diff 最近5次的交易時間差平均

In [25]:
# all_features_13 = pd.concat([all_features_13, all_features_18["bacno_cano_recent_no_5_loctm_acc_min_diff"]], axis=1)
# all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_7,latent_9,latent_10,latent_11,latent_12,latent_13,latent_14,latent_15,latent_16,bacno_cano_recent_no_5_loctm_acc_min_diff
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,916.500
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.236,0.218,0.493,0.282,0.355,0.678,0.000,0.093,0.000,2787.854
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,0.000
3,6716,157159,29967,1016.11,62,172946,247,50436,3281,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.000,0.000,0.030,1113.242
4,5975,105985,81305,713.66,62,182129,263,93775,5817,102,...,0.219,0.262,0.000,0.839,0.000,0.000,0.000,0.000,0.083,864.471
5,0,78377,2295,465.62,0,104918,451,0,5817,102,...,0.236,0.218,0.493,0.282,0.355,0.678,0.000,0.093,0.000,0.000
6,6411,94435,49219,1806.49,62,172624,339,0,5865,102,...,0.719,0.875,0.379,1.467,0.000,0.000,0.513,0.568,0.365,0.000
7,6769,112032,177989,526.88,62,34933,373,79200,5817,102,...,0.602,0.372,1.228,1.040,0.629,0.347,0.000,0.560,0.296,586.590
8,6092,92294,85535,201.39,62,64652,264,8335,3585,102,...,0.188,0.031,0.386,0.396,0.412,0.482,0.000,0.000,1.052,0.000
9,0,16279,110755,465.62,0,104447,451,0,5817,102,...,0.236,0.218,0.493,0.282,0.355,0.678,0.000,0.093,0.000,0.000
10,6882,49387,57083,0.00,0,210254,459,2467,0,102,...,0.294,0.333,0.563,0.091,0.000,0.600,0.000,0.116,0.000,425.130
11,0,24677,4485,465.62,0,104728,451,0,5817,102,...,0.236,0.218,0.493,0.282,0.355,0.678,0.000,0.093,0.000,1843.506
12,6883,40691,47685,513.80,0,172346,457,10045,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,635.658
13,6881,12981,178029,513.80,0,191233,457,86584,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,2962.267
14,6882,43457,161279,0.00,0,164857,459,2459,0,102,...,0.294,0.333,0.563,0.091,0.000,0.600,0.000,0.116,0.000,615.777
15,0,151054,197751,465.62,0,104917,451,0,5817,102,...,0.236,0.218,0.493,0.282,0.355,0.678,0.000,0.093,0.000,2878.883
16,6716,150887,4541,930.31,62,142028,329,37560,5820,102,...,0.219,0.262,0.000,0.839,0.000,0.000,0.000,0.000,0.083,1476.475
17,5575,159032,42064,0.00,62,114348,203,33794,2138,44,...,0.818,0.755,0.000,0.095,0.422,0.297,0.000,0.419,0.000,1640.040
18,6881,8200,5398,513.80,0,225727,457,59333,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,0.000
19,6881,152257,65948,513.80,0,153959,457,68930,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,806.923
20,6882,110356,133430,0.00,0,143657,459,2461,0,102,...,0.294,0.333,0.563,0.091,0.000,0.600,0.000,0.116,0.000,2682.900
21,0,86863,149723,465.62,0,105021,451,0,5817,102,...,0.236,0.218,0.493,0.282,0.355,0.678,0.000,0.093,0.000,0.000
22,6881,68339,115453,513.80,0,192156,457,59369,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,0.000
23,6881,161031,145047,683.25,0,121947,457,86584,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,1353.607
24,6881,147812,209978,513.80,0,150613,457,59333,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,1223.570
25,6769,29914,210026,298.10,62,195207,291,78438,3588,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.000,0.000,0.030,1439.030
26,6881,76903,83784,513.80,0,175543,457,74617,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,13.075
27,2724,106875,141524,513.80,0,91927,453,544,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.000,0.000,0.000,0.000
28,5630,157524,208050,747.35,74,21157,277,35812,5356,14,...,0.219,0.262,0.000,0.839,0.000,0.000,0.000,0.000,0.083,1423.897
29,0,62465,25295,465.62,0,104853,451,0,5817,102,...,0.236,0.218,0.493,0.282,0.355,0.678,0.000,0.093,0.000,8159.672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421635,5962,1105,8341,999.98,62,91728,317,77516,6031,102,...,0.818,0.755,0.000,0.095,0.422,0.297,0.000,0.419,0.000,8625.083
421636,5962,1105,8341,776.78,62,113517,317,77516,6031,102,...,0.818,0.755,0.000,0.095,0.422,0.297,0.000,0.419,0.000,550.917
421637,5962,1105,8341,999.98,62,93436,317,77516,6031,102,...,0.818,0.755,0.000,0.095,0.422,0.297,0.000,0.419,0.000,684.647
421638,5962,1105,8341,776.78,62,113400,317,77516,6031,102,...,0.818,0.755,0.000,0.095,0.422,0.297,0.000,0.419,0.000,0.000
421639,0,1105,8340,465.62,0,100959,451,0,5817,102,...,0.236,0.218,0.493,0.282,0.355,0.678,0.000,0.093,0.000,4328.687
421640,5962,1105,8341,776.78,62,113827,317,77516,6031,102,...,0.818,0.755,0.000,0.095,0.422,0.297,0.000,0.419,0.000,308.613
421641,5962,1105,8341,999.98,62,93535,317,77516,6031,102,...,0.818,0.755,0.000,0.095,0.422,0.297,0.000,0.419,0.000,1250.853
421642,6716,160471,43043,1028.77,62,183149,247,34949,5817,102,...,0.704,0.089,0.663,0.438,0.303,0.862,0.619,1.008,1.113,2002.143
421643,6752,154675,115418,716.41,26,72503,318,68603,5932,52,...,0.722,0.347,0.410,0.117,0.702,0.618,0.000,1.073,0.809,1768.470
421644,6752,154675,115418,873.69,26,3151,318,68603,5932,52,...,0.722,0.347,0.410,0.117,0.702,0.618,0.000,1.073,0.809,8343.054
421645,6752,154675,115418,244.49,26,21542,318,68603,5932,52,...,0.722,0.347,0.410,0.117,0.702,0.618,0.000,1.073,0.809,692.650
421646,6677,154675,115418,588.39,62,120925,251,26306,6022,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.000,0.000,0.030,2302.893
421647,6752,154675,115418,866.50,26,73249,318,68603,5932,52,...,0.722,0.347,0.410,0.117,0.702,0.618,0.000,1.073,0.809,5422.833
421648,6752,154675,115418,0.08,26,123322,318,68603,5932,52,...,0.722,0.347,0.410,0.117,0.702,0.618,0.000,1.073,0.809,2526.837
421649,6231,154675,115418,325.94,62,175847,277,18352,5817,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.000,0.000,0.030,5050.450
421650,6752,154675,115418,885.30,26,81612,318,68603,5932,52,...,0.722,0.347,0.410,0.117,0.702,0.618,0.000,1.073,0.809,437.146
421651,6752,154675,115418,906.60,26,211823,318,68603,5932,52,...,0.722,0.347,0.410,0.117,0.702,0.618,0.000,1.073,0.809,0.000
421652,6769,64349,122777,284.95,62,101026,251,78060,5817,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.000,0.000,0.030,1467.887
421653,6769,64349,122777,473.36,62,104828,251,77981,5817,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.000,0.000,0.030,8588.380
421654,6769,64349,122777,465.09,62,105147,286,77983,5817,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.000,0.000,0.030,2319.850
421655,6769,64349,122777,495.92,62,113232,251,77981,5817,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.000,0.000,0.030,0.000
421656,6769,106156,4897,859.57,62,142857,251,77989,5817,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.000,0.000,0.030,8180.123
421657,6231,162079,97150,1212.15,62,130950,257,13835,5817,102,...,0.219,0.262,0.000,0.839,0.000,0.000,0.000,0.000,0.083,5151.917
421658,6231,162079,97150,1282.55,62,202818,247,6476,5817,102,...,0.219,0.262,0.000,0.839,0.000,0.000,0.000,0.000,0.083,1183.813
421659,6854,155409,107022,1100.61,62,145525,319,53458,6031,102,...,0.946,0.766,0.000,0.117,0.387,0.325,0.000,1.259,0.809,5184.757
421660,5975,147326,79511,633.76,62,111228,343,87282,5817,102,...,0.212,0.054,0.377,0.409,0.351,0.444,0.000,0.000,0.035,5403.353
421661,6716,14305,136493,952.84,62,85839,245,48784,5859,102,...,0.000,0.286,0.000,1.073,1.026,0.184,0.243,0.427,0.226,9216.613
421662,5975,156543,137963,713.42,62,184921,263,98326,5817,102,...,0.219,0.262,0.000,0.839,0.000,0.000,0.000,0.000,0.083,12153.229
421663,6231,156543,137964,903.94,62,144434,251,17763,5817,102,...,0.314,0.072,0.171,0.374,0.045,0.000,0.000,0.000,0.030,1789.660
421664,6769,131985,98699,760.09,62,162804,251,78019,3294,102,...,0.219,0.262,0.000,0.839,0.000,0.000,0.000,0.000,0.083,515.920

#### bacon_cano_cnt 帳號&卡號綁一起的交易總次數

In [9]:
all_features_13 = pd.concat([all_features_13, all_features_18["bacon_cano_cnt"]], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_7,latent_9,latent_10,latent_11,latent_12,latent_13,latent_14,latent_15,latent_16,bacon_cano_cnt
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.0,0.000,0.0,80
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.236,0.218,0.493,0.282,0.355,0.678,0.0,0.093,0.0,23
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.294,0.155,0.443,0.222,0.000,0.351,0.0,0.000,0.0,18

#### bacno_cano_conam_cumsum_mean 該帳戶該卡號該筆刷卡前所有金額平均

In [10]:
all_features_13 = pd.concat([all_features_13, all_features_18["bacno_cano_conam_cumsum_mean"]], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_9,latent_10,latent_11,latent_12,latent_13,latent_14,latent_15,latent_16,bacon_cano_cnt,bacno_cano_conam_cumsum_mean
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.155,0.443,0.222,0.000,0.351,0.0,0.000,0.0,80,561.301
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.218,0.493,0.282,0.355,0.678,0.0,0.093,0.0,23,355.962
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.155,0.443,0.222,0.000,0.351,0.0,0.000,0.0,18,552.063

#### 2. bacno_cano_7_sleep_time_conam_lower_3000_cnt  帳號卡號最後幾天挑14筆交易的交易時間發生在睡覺時間且金額小於3000的次數

In [11]:
all_features_13 = pd.concat([all_features_13, all_features_18["bacno_cano_7_sleep_time_conam_lower_3000_cnt"]], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_10,latent_11,latent_12,latent_13,latent_14,latent_15,latent_16,bacon_cano_cnt,bacno_cano_conam_cumsum_mean,bacno_cano_7_sleep_time_conam_lower_3000_cnt
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.443,0.222,0.000,0.351,0.0,0.000,0.0,80,561.301,0
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.493,0.282,0.355,0.678,0.0,0.093,0.0,23,355.962,1
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.443,0.222,0.000,0.351,0.0,0.000,0.0,18,552.063,0

#### 2. bacno_cano_14_rolling_times_prime_time_fraud_cnt  帳號卡號最近幾筆14筆交易內的交易時間發生在盜刷熱門時段的次數

In [12]:
all_features_13 = pd.concat([all_features_13, all_features_18["bacno_cano_14_rolling_times_prime_time_fraud_cnt"]], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_11,latent_12,latent_13,latent_14,latent_15,latent_16,bacon_cano_cnt,bacno_cano_conam_cumsum_mean,bacno_cano_7_sleep_time_conam_lower_3000_cnt,bacno_cano_14_rolling_times_prime_time_fraud_cnt
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.222,0.000,0.351,0.0,0.000,0.0,80,561.301,0,12.0
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.282,0.355,0.678,0.0,0.093,0.0,23,355.962,1,14.0
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.222,0.000,0.351,0.0,0.000,0.0,18,552.063,0,10.0

#### 3. bacno_cano_sec_diff_latter 該筆與同帳戶卡號交易後一筆減前一筆的秒數

In [13]:
all_features_13 = pd.concat([all_features_13, all_features_18["bacno_cano_sec_diff_latter"]], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_12,latent_13,latent_14,latent_15,latent_16,bacon_cano_cnt,bacno_cano_conam_cumsum_mean,bacno_cano_7_sleep_time_conam_lower_3000_cnt,bacno_cano_14_rolling_times_prime_time_fraud_cnt,bacno_cano_sec_diff_latter
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.000,0.351,0.0,0.000,0.0,80,561.301,0,12.0,9575.0
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.355,0.678,0.0,0.093,0.0,23,355.962,1,14.0,4966.0
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.000,0.351,0.0,0.000,0.0,18,552.063,0,10.0,76914.0

#### bacno_cano_no_recent_7_conam_pos_trend 最近7次的交易金額的diff是不是平均為正

In [14]:
all_features_13 = pd.concat([all_features_13, all_features_18["bacno_cano_no_recent_7_conam_pos_trend"]], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_13,latent_14,latent_15,latent_16,bacon_cano_cnt,bacno_cano_conam_cumsum_mean,bacno_cano_7_sleep_time_conam_lower_3000_cnt,bacno_cano_14_rolling_times_prime_time_fraud_cnt,bacno_cano_sec_diff_latter,bacno_cano_no_recent_7_conam_pos_trend
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.351,0.0,0.000,0.0,80,561.301,0,12.0,9575.0,0.00
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.678,0.0,0.093,0.0,23,355.962,1,14.0,4966.0,-54.42
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.351,0.0,0.000,0.0,18,552.063,0,10.0,76914.0,-18.09

#### bacno_cano_conam_rolling_7_window_sum 該帳戶該卡號該筆刷卡的包含自己7次金額加總

In [15]:
all_features_13 = pd.concat([all_features_13, all_features_18["bacno_cano_conam_rolling_7_window_sum"]], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_14,latent_15,latent_16,bacon_cano_cnt,bacno_cano_conam_cumsum_mean,bacno_cano_7_sleep_time_conam_lower_3000_cnt,bacno_cano_14_rolling_times_prime_time_fraud_cnt,bacno_cano_sec_diff_latter,bacno_cano_no_recent_7_conam_pos_trend,bacno_cano_conam_rolling_7_window_sum
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.0,0.000,0.0,80,561.301,0,12.0,9575.0,0.00,3673.51
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.0,0.093,0.0,23,355.962,1,14.0,4966.0,-54.42,2482.74
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.0,0.000,0.0,18,552.063,0,10.0,76914.0,-18.09,3892.49

#### bacno_cano_conam_rolling_14_window_sum 該帳戶該卡號該筆刷卡的包含自己14次金額平均

In [17]:
all_features_13 = pd.concat([all_features_13, all_features_18["bacno_cano_conam_rolling_14_window_mean"]], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_15,latent_16,bacon_cano_cnt,bacno_cano_conam_cumsum_mean,bacno_cano_7_sleep_time_conam_lower_3000_cnt,bacno_cano_14_rolling_times_prime_time_fraud_cnt,bacno_cano_sec_diff_latter,bacno_cano_no_recent_7_conam_pos_trend,bacno_cano_conam_rolling_7_window_sum,bacno_cano_conam_rolling_14_window_mean
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.000,0.0,80,561.301,0,12.0,9575.0,0.00,3673.51,601.579
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.093,0.0,23,355.962,1,14.0,4966.0,-54.42,2482.74,383.249
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.000,0.0,18,552.063,0,10.0,76914.0,-18.09,3892.49,568.570

#### bacno_cano_conam_rolling_7_window_mean 該帳戶該卡號該筆刷卡的包含自己7次金額平均

In [18]:
all_features_13 = pd.concat([all_features_13, all_features_18["bacno_cano_conam_rolling_7_window_mean"]], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,latent_16,bacon_cano_cnt,bacno_cano_conam_cumsum_mean,bacno_cano_7_sleep_time_conam_lower_3000_cnt,bacno_cano_14_rolling_times_prime_time_fraud_cnt,bacno_cano_sec_diff_latter,bacno_cano_no_recent_7_conam_pos_trend,bacno_cano_conam_rolling_7_window_sum,bacno_cano_conam_rolling_14_window_mean,bacno_cano_conam_rolling_7_window_mean
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,0.0,80,561.301,0,12.0,9575.0,0.00,3673.51,601.579,524.787
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,0.0,23,355.962,1,14.0,4966.0,-54.42,2482.74,383.249,354.677
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,0.0,18,552.063,0,10.0,76914.0,-18.09,3892.49,568.570,556.070

#### bacno_cano_conam_rolling_3_window_mean 該帳戶該卡號該筆刷卡的包含自己3次金額平均

In [19]:
all_features_13 = pd.concat([all_features_13, all_features_18["bacno_cano_conam_rolling_3_window_mean"]], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,bacon_cano_cnt,bacno_cano_conam_cumsum_mean,bacno_cano_7_sleep_time_conam_lower_3000_cnt,bacno_cano_14_rolling_times_prime_time_fraud_cnt,bacno_cano_sec_diff_latter,bacno_cano_no_recent_7_conam_pos_trend,bacno_cano_conam_rolling_7_window_sum,bacno_cano_conam_rolling_14_window_mean,bacno_cano_conam_rolling_7_window_mean,bacno_cano_conam_rolling_3_window_mean
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,80,561.301,0,12.0,9575.0,0.00,3673.51,601.579,524.787,575.297
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,23,355.962,1,14.0,4966.0,-54.42,2482.74,383.249,354.677,234.660
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,18,552.063,0,10.0,76914.0,-18.09,3892.49,568.570,556.070,550.040

#### 加入bacno_cano_7_times_conam_max_by_no, bacno_cano_conam_rolling_14_window_max, bacno_cano_14_times_conam_max_by_no, bacno_cano_conam_cumsum_mean, bacno_cano_recent_no_5_loctm_acc_min_diff, bacno_cano_no_mean_loctm_acc_min_diff

In [26]:
all_features_13 = all_features_13.reset_index(drop=True)

In [27]:
all_features_13 = pd.concat([all_features_13, other_all_feature], axis=1)
all_features_13.head(3)

,acqic,bacno,cano,conam,csmcu,loctm,mcc,mchno,scity,stocn,...,bacno_cano_conam_rolling_7_window_sum,bacno_cano_conam_rolling_14_window_mean,bacno_cano_conam_rolling_7_window_mean,bacno_cano_conam_rolling_3_window_mean,bacno_cano_7_times_conam_max_by_no,bacno_cano_conam_rolling_14_window_max,bacno_cano_14_times_conam_max_by_no,bacno_cano_conam_cumsum_mean,bacno_cano_recent_no_5_loctm_acc_min_diff,bacno_cano_no_mean_loctm_acc_min_diff
0,6881,113261,38038,513.80,0,172652,457,59333,0,102,...,3673.51,601.579,524.787,575.297,2385.75,1458.33,2385.75,561.301096,189.563333,1620.892616
1,0,134508,45725,465.62,0,105114,451,0,5817,102,...,2482.74,383.249,354.677,234.660,1881.93,812.26,1881.93,355.962083,967.920000,5288.661364
2,6881,15408,188328,513.80,0,152458,457,59333,0,102,...,3892.49,568.570,556.070,550.040,776.57,683.25,1304.96,552.063333,1939.836667,6931.104902

#### 先刪掉幾個看是誰overfitting

In [6]:
all_features_13 = all_features_13.drop(["bacno_cano_7_sleep_time_conam_lower_3000_cnt.1",
                                       "bacno_cano_7_times_conam_max", # 跟bacno_cano_7_times_conam_max_by_no重複
                                       # "bacno_cano_no_mean_loctm_acc_min_diff", # 帳戶平均交易時間差 先拿掉看看
                                       "bacno_cano_14_times_conam_mean", # 跟bacno_cano_conam_rolling_14_window_mean重複
                                       # "bacno_cano_7_times_conam_mean",  # 考慮要不要加by no版本
                                       # "bacno_cano_3_times_conam_sum",  # 考慮要不要加by no版本
                                       # "bacno_cano_7_times_conam_sum",  # 考慮要不要加by no版本
                                       "bacno_cano_conam_rolling_7_window_mean", # 會跟bacno_cano_conam_rolling_7_window_sum有點疊到
                                       "bacno_cano_conam_rolling_14_window_mean", # 會跟bacno_cano_conam_rolling_7_window_sum有點疊到
                                       "bacno_cano_conam_cumsum_mean.1" # 跟bacno_cano_conam_cumsum_mean 重複
                                       ], axis=1)

### 輸出檔案

In [7]:
train_pre_2 = all_features_13[:-len(X_test_13)]
test_pre_2 = all_features_13[-len(X_test_13):]

print(train_pre_2.shape)
print(test_pre_2.shape)

train_pre_2 = pd.concat([train_pre_2, train_raw_13["fraud_ind"]], axis=1)

# print(train_pre_2.drop_duplicates().reset_index(drop=True).shape)
# print(train_pre_2.shape)

(1516988, 96)
(421665, 96)

In [8]:
train_pre_2.to_csv("train_pre_13_add_more_ftrs_2.csv", index=None)
test_pre_2.to_csv("test_pre_13_add_more_ftrs_2.csv", index=None)